import random

def guess(x):
    """Player tries to guess a random number generated by the computer."""
    random_number = random.randint(1, x)
    guess = None

    while guess != random_number:
        guess = int(input(f'Guess a number between 1 and {x}: '))
        if guess > random_number:
            print('Too high!')
        elif guess < random_number:
            print('Too low!')

    print(f"Congrats! You guessed the correct number: {random_number}")

# guess(10)

def computer_guess(x, secret_number):
    """Computer tries to guess a secret number provided by the player."""
    print(f"Your secret number is {secret_number}. The computer will try to guess it!")
    low, high = 1, x
    guess = None

    while guess != secret_number:
        guess = random.randint(low, high)
        feedback = input(f"Is {guess} too low (L), too high (H), or correct (C)? ").lower()

        if feedback == 'h':
            high = guess - 1
        elif feedback == 'l':
            low = guess + 1

    print(f"Yay! The computer guessed your secret number {secret_number} correctly.")

# Example usage:
# computer_guess(1000, 300)
